# Generated by Django 2.1.5 on 2019-10-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('investment_name', models.CharField(max_length=40)),
                ('capital_requirement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='data_commitment',
            fields=[
                ('commitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='data_fund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='data_fund_investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_call')),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_commitment')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_fund')),
            ],
        ),
        migrations.AddField(
            model_name='data_commitment',
            name='fund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_fund'),
        ),
    ]
