# Generated by Django 2.1.5 on 2019-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_fund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=40)),
            ],
        ),
    ]
