# Generated by Django 2.1.5 on 2019-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_data_commitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.IntegerField()),
                ('date', models.DateField()),
                ('investment_name', models.CharField(max_length=40)),
                ('capital_requirement', models.IntegerField()),
            ],
        ),
    ]
