# Generated by Django 2.1.5 on 2019-10-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_data_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_fund_investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_call')),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_commitment')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.data_fund')),
            ],
        ),
    ]
